project:
  type: website
  preview:
    port: 4200

website:
  title: "Lukman A. Soboyejo"
  page-navigation: true
  site-url: "https://lsoboyejo.netlify.app/"
  
  page-footer:
    left:  "© 1992-2025, Lukman A. Soboyejo"
    background: "#9172be"
    right:
      - icon: github
        href: https://github.com/lukeng200
      - icon: twitter
        href: https://twitter.com/Hadeboye
      - icon: envelope
        href: lsoboyejo@student.unimelb.edu.au
        
  # twitter-card:
  #   creator: "@lucas_shubby"
  #   card-style: summary_large_image


# site navigation
  navbar:
    background: "#9172be"
    right:
      - href: experience/index.qmd
        text: Experience
      - href: education/index.qmd
        text: Education
      - text: Publications
        href: publications/index.qmd
      - text: News
        href: news/index.qmd
      - text: Engagements
        href: Engagements/index.qmd
      - text: Blog
        menu:
        - text: All post
          href: blog/index.qmd


date-format: "D MMMM YYYY"
freeze: true

format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: ''
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    highlight-style: monokai
    code-link: true



# comments:
#   giscus:
#     repo: lukeng200/lsoboyejo-webpage

editor: visual



