---
layout: default
title:  'More Information - About Me'
---

<p class="lead">

<a href="cv.pdf">Click here</a> to view my CV as an isolated pdf.

</p>

## Bio

The following bio and [**this photo**](../images/Me.jpg) may be used in media releases without further permission.

> **Lukman Adeboye Soboye** is currently a graduate researcher at the [Department of Ecosytem and Forest services](https://ecosystemforest.unimelb.edu.au/research) from the [University of Melbourne](https://www.unimelb.edu.au/). <br><br> My background interest and focus have always been about water and earth sciences. The need to gain more insight about environmental assessment and management prompted me to seek new challenge elsewhere (MSc and PhD sojourn).</a> In the quest of moving around, I have acquired numerous skill sets such as data analysis and visualisation (using R and a bit of Python) and models, GIS, GPR, remote sensing, river geomorphic mapping, and more in tackling and managing environmental complexities.</a> <br><br> My undergraduate project was about **the assessment of limestone mining impact on groundwater quality, Sagamu, Ogun State, Nigeria.** The project was supervised by <a href = "https://funaab.edu.ng/awomeso-julius-awonusi/"> Prof. Julius Awomeso.</a> <br><br> My Master's project was on **Different processes affecting long-term Ravenna coastal drainage basins (Italy): implications for water management**. The project was supervised by <a href = "https://www.unibo.it/sitoweb/m.antonellini/en">Prof. Marco Antonellini</a> and <a href = "https://www.unibo.it/sitoweb/beatrice.giambastiani/en">Prof. B.M.S Giambiastini</a>.<br><br>However, I am currently working on predicting river channel disturbance in response to urbanisation. The project is supervised by Dr Kathryn Russel, Prof. Tim Fletcher, and Dr Jasper Kunapo.

::: columns
::: {.column width="30%"}
<ul class="fa-ul">

<li><a href="https://github.com/lukeng200/lukeng200.github.io/raw/master/CV.pdf"><i class="fa-li fa-regular fa-file-pdf"></i>Curriculum Vitae</a></li>

<li><a href="https://scholar.google.com.au/citations?hl=en&user=l63u3A4AAAAJ"><i class="fa-li ai ai-google-scholar" style="padding-top:4px;"></i>Google Scholar</a></li>

</ul>
:::

::: {.column width="30%"}
<ul class="fa-ul">

<li><a href="https://orcid.org/0000-0002-2953-1150"><i class="fa-li ai ai-orcid" style="padding-top:4px;"></i>ORCID</a></li>

<li><a href="https://github.com/lukeng200"><i class="fa-li fa-brands fa-github"></i>GitHub</a></li>

</ul>
:::
:::

## Address

**Mail:** School of Ecosystem and Forest Sciences\](https://ecosystemforest.unimelb.edu.au/), [University of Melbourne](https://www.unimelb.edu.au/), 500 Yarra Boulevard, Richmond, Victoria 3121, Australia.

**Office:** Engineering Facilities, Building 903, Burnley campus, [University of Melbourne](https://www.unimelb.edu.au/), 500 Yarra Boulevard, Richmond, Victoria 3121, Australia.

::: mapouter
::: gmap_canvas
<iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=500%20Yarra%20Boulevard,%20Richmond,%20Victoria%203121,%20Australia&amp;t=&amp;z=13&amp;ie=UTF8&amp;iwloc=&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0">

</iframe>

<a href="https://putlocker-is.org">putlocker</a><br>

```{=html}
<style>.mapouter{position:relative;text-align:right;height:500px;width:600px;}</style>
```
<a href="https://www.embedgooglemap.net">google map in website</a>

```{=html}
<style>.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}</style>
```
:::
:::

## Qualifications

-   First School Leaving Certificate (FSLC), 2003.
-   Junior High School Certificate, 2006.
-   West African Senior School Certificate (WASSCE), 2009.
-   B.Sc., Federal University of Agriculture, Abeokuta (FUNAAB), 2015.
-   M.Sc., University of Bologna, Italy, 2020.(Joint Degree)
-   M.Sc., University of Algarve, Spain, 2020. (Joint Degree)
-   Ph.D. in View, University of Melbourne, 2022-2025.
